title: Ted Shaowang
logo: /assets/img/portrait.png
description: PhD Student @ UChicago CS
google_analytics: G-YXM4LW31FP
theme: jekyll-theme-minimal
email: swjz@uchicago.edu

github:
  is_project_page: false
